version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: blocket_sql
    environment:
      SA_PASSWORD: "Super86Secret@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      # Mount your db scripts into the container
      - ./db:/usr/config
    command: >
      bash -c "
        /opt/mssql/bin/sqlservr &
        sleep 25 &&
        /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P 'Super86Secret@' -i /usr/config/init.sql &&
        /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P 'Super86Secret@' -i /usr/config/seed.sql &&
        wait
      "
